### PR TITLE
Fix the spinner (main site and it's wonkiness)

### LINKED ISSUE #3394: [main site] delay spinner does not spin

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@jedp - could I get a quick review?

@jrgm - should we merge this into train-2013.05.08 as well?

fixes #3394

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@jedp - An ephemeral instance is already set up for testing purposes - spinner.personatest.org.

**Comment by jedp** [comment]
trying on a v1.0.1 unagi ...

**Comment by jedp** [comment]
I like this a lot.  I like the spinner smaller, and it certainly looks centered on device.  r=me.

**Comment by shane-tomlinson** [comment]
Jed just informed me that we can allow this to go into dev to make its way to prod in time. It doesn't look like we need to hotfix stage.

**Pull request merged**
