### PR TITLE
Individually revert all the accidentally-added commits to train-2013.03.01.

### PR DESCRIPTION
**Pull request by jaredhirsch**
This is a lot more verbose than trying to undo everything at once, but it's also a lot clearer what happened and how it was fixed.

Maybe just use this?

### CODE REVIEW

**Comment by jaredhirsch** [comment]
@edmoz I was feeling suspicious about the amount of magic involved in `git reset` tricks, so I just reverted them all individually via

```
for i in `git rev-list 0d62ce67^..899ae402`; do git revert --no-edit -s $i; done
```

I'm fairly certain this covers **everything**.

**Comment by jaredhirsch** [comment]
@lloyd @jrgm second opinion? this is a fix for an accidental push to the wrong remote (mozilla instead of edmoz). We've tried messing with `git reset --keep` but it didn't seem like it was capturing all the changes, see ed's earlier PR #3159.

edit: got the PR #s wrong.

**Comment by jrgm** [comment]
Here's an idea. Cut a branch off the sha for train-2013.03.01, then swap the names of the two trains. Or am I on crack.

**Comment by jrgm** [comment]
Actually, I am on crack. But **if** we have to ship a hotfix for train-2013.03.01, I might prefer to branch from 0d62ce67 to train-2013.03.01-redux and ship from there. (And then just delete this branch).

**Comment by jaredhirsch** [comment]
@jrgm that's cool. in that case, mind if we just merge this in anyway? I don't want to orphan any existing branches, regardless of whether we hotfix release from this or another branch.

**Comment by jrgm** [comment]
@6a68 - yeah, I guess merge this in.

**Comment by edwindotcom** [comment]
Thanks guys. @jrgm we went down a few different paths and decided this one was the safest.

**Comment by jaredhirsch** [comment]
arright. :beers: this was fun

**Pull request merged**
