### PR TITLE
[load_gen] add option --interaction-data, to allow tuning/disabling of rate of interaction_data

### PR DESCRIPTION
**Pull request by jrgm**
Also piggybacking a small fix to error reporting on a rare error.

### CODE REVIEW

**Comment by jrgm** [comment]
Forgot to note. Fixes GH-3063

**Comment by kparlante** [comment]
Agreed, this needs to be configurable on the load_gen side. This works for me. The default could be to leave it at zero, at least until its turned on most places (like staging).

**Comment by jrgm** [comment]
Hmm, yeah could go either way on the default value, but I'm leaning a bit to it being on by default.

**Comment by kparlante** [comment]
Fair enough, whatever works best for you. +r

**Pull request merged**
