### PR TITLE
Use Date.now() to reduce memory allocation

### PR DESCRIPTION
**Pull request by junosuarez**

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@jden - thanks for the PR! On the surface, I am comfortable with this change. 

ignore the deleted link

**Comment by shane-tomlinson** [comment]
@jden - I am having trouble finding references to where memory usage is reduced using Date.now() vs new Date(). I see some articles on performance in the browsers, but little else.

@lloyd - would nodegrind or whatever your memory allocation tool is called be up to the task of testing this?

**Comment by jaredhirsch** [comment]
@shane-tomlinson I've been thinking about this. I don't want to chase @jden away (hi! thanks for the PR :beers:), but the verifier is compute-bound, allocating one or two new objects in memory (i.e. `new Date` vs `Date()`) doesn't seem like an optimization that will affect the runtime meaningfully.

@jden thoughts? Shane's been tagging more bugs as good-first-bug the past week or so, those are an ideal way to get involved with the codebase, that'll make more of a difference than this particular microoptimization IMO. Feel free to ping on #identity in mozilla IRC if you want help as you go. And, welcome to the project :)

**Comment by callahad** [comment]
At the same time, this avoids creating two objects, and frankly, reads a little more clearly to me. I don't have to mentally do the type coercion in my head. :)

It's small, but I think it's strictly better.

**Comment by seanmonstar** [comment]
Yea, Date.now() was designed exactly for this purpose. Easy enough to
merge.

**Comment by shane-tomlinson** [comment]
I generally agree with @callahad that this change results in a more readable verifier, but it does result in inconsistency elsewhere in the code:

```
➜  lib git:(dev) ✗ rgrep "new Date" .
./db/json.js:function now() { return Math.floor(new Date().getTime() / 1000); }
./db/json.js:      d = new Date(db.staged[db.stagedEmails[email]].when);
./db/json.js:      when: (new Date()).getTime()
./db/json.js:      when: (new Date()).getTime()
./db/json.js:  db.idp[domain] = new Date().getTime();
./db/json.js:  var lastSeen = db.idp[domain] ? new Date(db.idp[domain]) : null;
./db/mysql.js:function now() { return Math.floor(new Date().getTime() / 1000); }
./db/mysql.js:                 else if (rows && rows.length > 0) cb(err, new Date(rows[0].ts * 1000));
./db/mysql.js:      else cb(null, new Date(rows[0].ts * 1000));
./db/mysql_wrapper.js:          var reqTime = new Date() - work.startTime;
./db/mysql_wrapper.js:        startTime: new Date()
./keysigner/ca.js:            {issuer: hostname, issuedAt: new Date(), expiresAt: expiration},
./keysigner/keysigner-compute.js:    var expiration = new Date();
./keysigner/keysigner-compute.js:    expiration.setTime(new Date().valueOf() + m.validityPeriod);
./load_gen/common.js:  var t = new Date(((new Date()).getTime() - ctx.sessionStartedAt) + ctx.session.server_time);
./load_gen/crypto.js:    var expirationDate = new Date(obj.now.getTime() + (2 * 60 * 1000));
./load_gen/crypto.js:    if ((assertion.expirationDate - new Date()) < (60 * 1000)) {
./logging.js:    timestamp: function () { return new Date().toISOString(); },
./metrics.js:      timestamp: function () { return new Date().toISOString(); },
./metrics.js:  entry.at = new Date().toUTCString();
./primary.js:  var now = new Date();
./secrets.js:  return new Date(readAndParseCert(name, dir).iat);
./static/views.js:  res.setHeader('Date', new Date().toUTCString());
./verifier/certassertion.js:    new Date(), function(issuer, next) {
./wsapi/address_info.js:          if ((new Date() - when) < config.get('idp_offline_grace_period_ms')) {
./wsapi/authenticate_user.js:      var startTime = new Date();
./wsapi/authenticate_user.js:        var reqTime = new Date() - startTime;
./wsapi/interaction_data.js:      kpi.timestamp = new Date().getTime();
./wsapi/session_context.js:      server_time: (new Date()).getTime(),
./wsapi/stage_email.js:    if (last && (new Date() - last) < config.get('min_time_between_emails_ms')) {
./wsapi/stage_email.js:                  ((new Date() - last) / 1000.0) + "s elapsed");
./wsapi/stage_reset.js:    if (last && (new Date() - last) < config.get('min_time_between_emails_ms')) {
./wsapi/stage_reset.js:                  ((new Date() - last) / 1000.0) + "s elapsed");
./wsapi/stage_transition.js:    if (last && (new Date() - last) < config.get('min_time_between_emails_ms')) {
./wsapi/stage_transition.js:                  ((new Date() - last) / 1000.0) + "s elapsed");
./wsapi/stage_user.js:    if (last && (new Date() - last) < config.get('min_time_between_emails_ms')) {
./wsapi/stage_user.js:                  ((new Date() - last) / 1000.0) + "s elapsed");
./wsapi.js:  var startTime = new Date();
./wsapi.js:    var reqTime = new Date() - startTime;
./wsapi_client.js:  return new Date();
./wsapi_client.js:  recentLatency = ((new Date() - startTime) + (recentLatency * (num - 1))) / num;
./wsapi_client.js:        context.sessionStartedAt = new Date().getTime();
➜  lib git:(dev) ✗ rgrep "Date.now" .
./templates.js:  bundle.lastGen = Date.now();
```

```
➜  bin git:(dev) ✗ rgrep "new Date" .
./keysigner:  var startTime = new Date();
./keysigner:    var reqTime = new Date - startTime;
./load_gen:var lastPoll = new Date();
./load_gen:    var now = new Date();
./load_gen:  var wakeUpIn = 1000 - (new Date() - lastPoll);
./verifier:  var startTime = new Date();
./verifier:    var reqTime = new Date - startTime;
./verifier:        expires : new Date(r.success.expires).valueOf()
➜  bin git:(dev) ✗ rgrep "Date.now" .
```

FWIW, all backend tests pass with this change.

**Comment by shane-tomlinson** [comment]
@jden - Thank you very much for the pull request. I realize there is some contention over merging this PR, nobody wants to drive away community contributors. I agree with @callahad that your change improves the readability of that section of code, I am worried about the inconsistency introduced since we have standardized on `new Date` in all but one location.

I see two ways around the inconsistency:
- update all `new Date`s to be `Date.now()`
- avoid the inconsistency by not introducing it.

I am hesitant to change all instances of `new Date()` to `Date.now()`

As @6a68 points out, I have been tagging issues with the "good first bug" label. I would love to work with you to smash one of those!

**Comment by callahad** [comment]
> I am hesitant to change all instances of new Date() to Date.now()

Why? :)

**Comment by shane-tomlinson** [comment]
@callahad - because it seriously expands the scope of the PR.

**Comment by callahad** [comment]
@shane-tomlinson Gotcha, thanks man!

**Comment by junosuarez** [comment]
@shane-tomlinson Thanks for the feedback - I opened this PR after casually browsing through the source, fixing things as I went along. I definitely understand the desire for consistency, though! Have you thought about splitting this project into multiple repositories, separating out the fallback IDP from the verification service?

@callahad I'd be happy to put together a PR converting all instances of new Date to Date.now, but yes, it is a much larger PR (as the above grep shows)

**Pull request closed without merging**
