### PR TITLE
Issue 3407 mobile buttons

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@jedp - could I get a review of this one?

Clean up buttons on mobile.

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@jedp - I have an ephemeral instance set up already - "mobile-buttons.personatest.org" that you can use to test.

**Comment by jedp** [comment]
Awesome that you set up an ephemeral instance to make this easy to test.  Checking it out now.

**Comment by jedp** [comment]
Hmm.  Doesn't look right on device.  I presume you're testing on desktop and you're getting completely different results?  Great.



Also, the spinner began spinning the word 'loading' before the spinner appeared.  Maybe remove the alt text?

**Comment by shane-tomlinson** [comment]
B2G uses Gecko 19, which uses the old flex-box. !@$!@^

**Comment by jedp** [comment]
I think it might actually be gecko 18

**Comment by jedp** [comment]
Buttons look great now.

There's a weird problem, though, with the keyboard flickering away and reappearing on email input.  This could be wrong, but it sort of seems like the dialog is trying to resize itself while text is being entered?

I'm trying the text input UI Test app on the phone, using the input type='email' field, and I can't get it to misbehave in the same way.

Yeah, and then sending the device to use firefoxos.persona.org, the problem is not evident.  So there must be something in this code that's causing the dialog to do something to dismiss and then recall the keyboard.  Hmm.

**Comment by shane-tomlinson** [comment]
@jedp - that strange flickering I saw too and fixed in a different PR - #3419, commit 277c61d218c6255da0f58a7dbea033f111caa8bd. Want me to cherry-pick that fix over to this?

I'll rebase now because I merged stuff into dev after I pushed this PR.

**Comment by jedp** [comment]
Sweet.  Testing now on mobile-buttons

**Comment by jedp** [comment]
Looks beautiful on device.  Nice fix.

**Comment by jedp** [comment]
Tests pass, looks good, r=me.  merging

**Pull request merged**
