### PR TITLE
Update privacy policy, in accordance with Bug 848506

### LINKED ISSUE #2922: Privacy Policy has outdated, scary bullet point
At the very top of https://login.persona.org/privacy is this bullet:

> As part of the normal operation of the Persona service, Mozilla will retain a log of which sites you have disclosed your email to.

AFAIK, we are not logging this. Can we please get legal review and remove this bullet?

@benadida, what's the next step? Should I file a Bugzilla bug targeted at Jishnu or the Legal team in general?

### PR DESCRIPTION
**Pull request by callahad**
https://bugzilla.mozilla.org/show_bug.cgi?id=848506

Fixes #2922

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@callahad - Is this blocking on anything or can it be merged?

**Comment by callahad** [comment]
I'm blocking on the actual Bugzilla bug getting closed as resolved. Don't want to touch legal things without that :)

**Comment by jaredhirsch** [comment]
Just now in IRC:

```
benadida        callahad: does this https://bugzilla.mozilla.org/show_bug.cgi?id=848506 from 
                Jishnu answer your question? I think it's ready to go.
```

**Comment by callahad** [comment]
We're good. Dropping myself from the bug assignment.

Someone else please grab this and verify my pull request against the text of the source document. Then hit the big green button. :)

**Comment by jaredhirsch** [comment]
read through it, lgtm! much less creep factor overall, nice work @callahad! thanks for pushing on this.

**Pull request merged**
