### PR TITLE
Remove reference to locale/compile-json.sh.

### PR DESCRIPTION
**Pull request by ozten**
Conservative fix. See Issue#3683 for another suggestion.

Fixes Issue#3683

### CODE REVIEW

**Comment by callahad** [comment]
I had to `mkdir resources/static/i18n`, but after that things appeared to compile fine. The resulting RPM includes compiled json/js files in that directory.

So, r+

**Comment by ozten** [comment]
Thanks for the review!

The old script did ensure this directory exists, I'll add that to the rpm spec

**Comment by jrgm** [comment]
I have built the rpm successfully with this change. I'll note that there are two subtle differences 1) all the metadata is now squashed into a single string keyed by `Project-Id-Version`, and 2) newlines in text strings are no longer escaped. e.g., 

```
-      "Removing the last address will cancel your Persona account.\\nAre you sure you want to continue?": [                
+      "Removing the last address will cancel your Persona account.\nAre you sure you want to continue?": [   
```

**Comment by ozten** [comment]
Great catches! We'll see in stage if newlines are significant. I didn't see any issues in http://translate.123done.org/

**Comment by jrgm** [comment]
Yeah, the one place where there is a newline looks correct on translate.personatest.org (an alert on main site).

**Pull request merged**
