### PR TITLE
Set the image sizes

### PR DESCRIPTION
**Pull request by shane-tomlinson**
issue #2483

### CODE REVIEW

**Comment by callahad** [comment]
How does this handle the scaling / responsive design aspects of the page? (I'll pull and investigate myself in a second)

**Comment by shane-tomlinson** [comment]
@callahad - great question, I meant to check before I issued the PR but got side tracked.

**Comment by callahad** [comment]
Answer: It doesn't scale proportionally :)

Resized browser showing squished images

**Comment by shane-tomlinson** [comment]
Closing and the original issue as WONTFIX.

**Pull request closed without merging**
