### PR TITLE
Add statsd metric for looking up /.well-known/browserid

### LINKED ISSUE #1704: add statsd metrics to /wsapi/address_info for /.well-known/browserid lookup times via proxy
add statsd metrics to /wsapi/address_info for /.well-known/browserid lookup elapsed times via http proxy

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Who wants to take it?

fixes #1704

### CODE REVIEW

**Comment by jaredhirsch** [comment]
High-level question: is it better to record the elapsed time and do the math inside the app, or is it better for the app to log timestamps so that arbitrary intervals can be measured downstream?

I'm not sure of the answer.

**Comment by jrgm** [comment]
Re: @6a68's question: don't we get both a timestamped logline **and** a statsd metric from the new logging arrangement?

**Comment by shane-tomlinson** [comment]
@6a68 - updated to handle success and failure cases separately.

**Comment by shane-tomlinson** [comment]
This is what an entry looks like in the logs:

```
{"elapsed":246,"level":"info","message":"elapsed_time.deep_fetch_well_known.error","timestamp":"2013-10-16T13:24:43.255Z"}
```

**Comment by jaredhirsch** [comment]
OK, looking now.

**Comment by jaredhirsch** [comment]
looks good, tests passing. R+, merging in. :beers:

**Pull request merged**
