### PR TITLE
BrowserID.persona_test_user() with unit tests

### PR DESCRIPTION
**Pull request by klrmn**
this has not been plumbed into any actual tests yet

### CODE REVIEW

**Comment by klrmn** [comment]
@jedp - in terms of what I am aware the bidpom BrowserID class needs, personatestuser.org is working. In terms of writing unit tests, we should contemplate how many layers of testing test tools makes sense or whether the tests making use of the tools are test enough.

@davehunt, @zac, @6a68 - 
This method should just Do The Right Thing for actual client projects like marketplace-tests. 

Since tests run on 123done.org and such need to know which environment they are in (dev/stage/prod) to use this, another layer is needed to detect the env from the --baseurl. I'm still contemplating the possible ways of doing this.

**Comment by klrmn** [comment]
oh, and plumbing this into the various test sets should speed them up considerably.

**Comment by jaredhirsch** [comment]
I guess it's not clear to me what the intent of this persona_test_user is, exactly. Can you provide some explanation?

Is this a way to create test users outside of the regular flow?

**Comment by klrmn** [comment]
@6a68 - many test cases have 'registered user exists' as a precondition. this method gives them exactly that, without using selenium, so it runs faster.

the test(s) that test creation of users will go thru the regular steps using selenium, this is just for use in preconditions.

**Comment by jaredhirsch** [comment]
ah, ok. just looked at personatestuser.org and it made sense. Definitely good to have out-of-band ways to create users, rather than depending on the creation flow we're supposed to be testing.

**Pull request merged**
