### PR TITLE
Implement onmatch in the Observer API

### LINKED ISSUE #2017: add different callback and discourage onready()
new callback should be something like onstatusquo(), which gets called if neither onlogin nor onlogout are about to be called. We should then phase out onready().

### LINKED ISSUE #2648: Add new optional callback, onmatch, to watch()
See mozilla/id-specs@0ad12419034273e888992305f37effbd2b4e4044

`id.watch` should have a third callback, `onmatch` that is optional and is invoked whenever the browser's state matches the value of `loggedInUser`.

This would change our possible callback sequences from:
1. `onlogin` then `onready`
2. `onlogout` then `onready`
3. `onready`

To
1. `onlogin` then `onready`
2. `onlogout` then `onready`
3. `onmatch` then `onready`

### PR DESCRIPTION
**Pull request by callahad**
Closes #2648
Closes #2017

### CODE REVIEW

**Comment by jaredhirsch** [comment]
@callahad how did you test this manually? I want to be sure I understand your steps before merging in.

**Comment by callahad** [comment]
@6a68 Use the "Example RP" on 127.0.0.1:10001 -- you can set `loggedInUser` to various things and watch what callbacks get called.

**Comment by jaredhirsch** [comment]
I'll finish reviewing this morning + merge in

**Comment by jaredhirsch** [comment]
r+

**Pull request merged**
