### PR TITLE
Add email type (primary or secondary) to DOM

### PR DESCRIPTION
**Pull request by graingert**
Add email type (primary or secondary) to DOM

This allows my user style to embolden my primary email

### CODE REVIEW

**Comment by graingert** [comment]
"Executing your before_install (sudo apt-get install libgmp3-dev) took longer than 8 minutes and was terminated."

**Comment by shane-tomlinson** [comment]
@graingert - Thanks for the PR!  Do you want these classes to only be assigned in the manage page or do you want these to be applied in the dialog?  The PR as written applies classes to the manage page.

**Comment by shane-tomlinson** [comment]
@graingert - Can you define the concrete use case of this PR?  

Once BigTent comes online, all Yahoo, GMail and Hotmail addresses are going to be marked "primary" as well. Is that going to affect what you are trying to do?

**Comment by graingert** [comment]
This is only for my personal userstyle that changes the style of .secondary and .primary

**Comment by shane-tomlinson** [comment]
@graingert - If your styling should be applied to the dialog, can you add the appropriate logic to browserid/resources/static/dialog/views/pick_email.ejs as well?

**Comment by shane-tomlinson** [comment]
@graingert - yo, ping. This is suffering from bit rot. If you want this merged in, can you rebase and add the appropriate logic to resources/static/dialog/views/pick_email.ejs as well?

**Comment by lloyd** [comment]
closing after 2 months of inactivity.  please re-open with a new commit if still desired.

In general, us doing this would imply that our DOM classes are an external contract that people can rely on.  That's a bit of commitment that scares me.  

Further, Given the way that the dialog works now, I'm not sure this is possible (we don't _know_ the email type in the front end until it's actually selected)

**Pull request closed without merging**
