### PR TITLE
Generate include js

### PR DESCRIPTION
**Pull request by callahad**
This is a first step toward #1199 and #1971.

Reviewer: It should be easiest to follow this if you look at each commit individually -- I took care to make sure the progression was natural.

### CODE REVIEW

**Comment by fmarier** [comment]
r+

Thanks a lot for breaking this up in multiple commits, it was really easy to review!

**Comment by seanmonstar** [comment]
My only thought is if there's a way to preserve the history onto the `_include.js` file, so we can `git blame` and understand when something looks crazy.

**Comment by callahad** [comment]
I don't believe there's an easy way to do that which preserves the readability the commit sequence :(.

Boo for Git only doing heuristic-based rename tracking.

**Comment by seanmonstar** [comment]
This sounds nuts, and forget it if the value doesn't seem there, but would this work?

Starting from the top: rename include.js to _include.js in a commit, then create the _files, deleting lines from _include.js in another commit. Then, all the left over lines still have history?

**Comment by callahad** [comment]
That would probably get us there, but at the cost of muddling the actual commit history (versus the blame history), which makes it harder to verify that the snippets do indeed yield a result identical to the original file.

(In b83eb67, the previous include.js is still in the repo, so any mismatch on generation would show up...)

The `_include.js` snippet is less than 430 SLOC -- I'm inclined to say good idea, but not worth it. Or at least, you're welcome to do it if you think it'd be significantly valuable.

**Comment by shane-tomlinson** [comment]
@callahad - This is HOT! I like this approach and have wanted it for a long time. Aside from the benefits you point out, a split up include.js should allow us to write front end unit tests that exercise various code paths [see #483].

Some suggestions:
- include.js is only generated in postinstall.js. If we are editing include.js and it needs to be re-built, there should be a mechanism to automatically do this. Perhaps in lib/static/views.js, where it fetches include.js if you check to see if the served resource needs to be rebuilt. We do this for other resources; see the /build/code_version.js route for an example. Calling generate_include.js from within a route probably necessitates making it asynchronous.
- Our generated resources have been placed into the `build` subdirectory of resources/static. If you place include.js into there, no need to add include.js to .gitignore and no danger of a stale version being served up by static middleware if a component was updated.
- Perhaps split BrowserSupport out into its own module. We have one in resources/static/common/js/browser-support.js and maybe these can be shared.
- The component resources should all have the license at the top. All but the first will be stripped during minification.
- Can the winchan.js and jschannel.js be shared with the resources already in resources/static/common/js/lib? It would be great if we could make updates to either of these in one place and have the changes reflected everywhere.
- The test in tests/jshint-test.js may need to be updated (I have not run this)
- To facilitate unit testing, it would be nice to be able to call some initialization function in include.js that allows us to mock in components like WinChan and JSChannel. In the built version, the initialization function would be called with the real WinChan and JSChannel.

**Comment by callahad** [comment]
@shane-tomlinson My immediate goal was to end up with an on-disk representation (including paths, etc) that was identical to before this pull request. All of those suggestions sound like solid "next steps." I'm going to go ahead and merge this, then work on another pull request to handle the shared components.

**Comment by jrgm** [comment]
no problems noted in stage train-2013.03.01

**Pull request merged**
