### PR TITLE
set secureProxy=true when running behind an ssl proxy

### PR DESCRIPTION
**Pull request by jrgm**
I'm not really thrilled with this change (1. should I add a config to say 'over ssl but using ssl termination out of process, and 2. client-sessions should be easier to use/better documented for this very common case).

### CODE REVIEW

**Comment by jrgm** [comment]
I guess I didn't explain the "why" of this change: basically the upgrades in client-session and its dependent cookies leads to what was pointed out in https://github.com/mozilla/node-client-sessions/issues/30#issuecomment-36080390. I'd also noticed a couple of weeks ago that awsbox deployments were not setting cookies for /wsapi (and probably a production deploy would have been broken too).

**Comment by jaredhirsch** [comment]
Thanks @jrgm! Any thoughts on how we could test this bug fix? (I'm happy to write the tests if you're not up for it, I could use a guide though--been a while.)

**Comment by jrgm** [comment]
@6a68 - added a test for this. Please have a look when you get spare time.

**Comment by jaredhirsch** [comment]
:beers:

**Comment by jaredhirsch** [comment]
@jrgm Works for me. About your comments in the pull request, if you think a config would be good, go ahead and file a followup bug.

**Pull request merged**
