### PR TITLE
catch urls that express cannot handle and return 404

### PR DESCRIPTION
**Pull request by zaach**
fixes issuee #2887

### CODE REVIEW

**Comment by jrgm** [comment]
@zaach works for me (and thanks for isolating the try; not sure how much it matters in this case, but I do know what I said about try is true).

I think, though, you should add a log message when the exception occurs.

**Comment by zaach** [comment]
@jrgm thanks, rebased and added logging

**Comment by shane-tomlinson** [comment]
A failure is reported when running `npm test` even though I see no obvious failures:

```
➜  browserid git:(issue_2887_500_urls) ✗ npm test

> browserid@1.0.0-b1 test /Users/stomlinson/development/browserid
> ./scripts/test

>>> Now Running: API level unit tests using MySQL

Can't run tests: can't connect to the database

>>> Now Running: API level unit tests using a JSON database
tests/account-cancel-test.js
···········  
  ✓ OK » 11 honored (4.897s) 
  tests/add-email-with-assertion-test.js
····················  
  ✓ OK » 20 honored (4.244s) 
  tests/address-info-test.js
·······················  
  ✓ OK » 23 honored (5.491s) 
  tests/auth-with-assertion-test.js
················  
  ✓ OK » 16 honored (6.033s) 
  tests/bcrypt-compatibility-test.js
··  
  ✓ OK » 2 honored (0.027s) 
  tests/ca-test.js
···  
  ✓ OK » 3 honored (0.010s) 
  tests/cache-header-tests.js
······················································  
  ✓ OK » 54 honored (3.459s) 
  tests/cef-logging.js
·········  
  ✓ OK » 9 honored (0.690s) 
  tests/cert-key-test.js
················  
  ✓ OK » 16 honored (4.943s) 
  tests/coarse-user-agent-parser-test.js
··  
  ✓ OK » 2 honored (0.049s) 
  tests/conformance-test.js
··············  
  ✓ OK » 14 honored (0.093s) 
  tests/cookie-session-security-test.js
········  
  ✓ OK » 8 honored (3.476s) 
  tests/db-test.js
·····························································  
  ✓ OK » 61 honored (1.049s) 
  tests/double-stage-updates-password.js
············  
  ✓ OK » 12 honored (4.459s) 
  tests/email-throttling-test.js
·············  
  ✓ OK » 13 honored (4.254s) 
  tests/forgotten-pass-test.js
···················································  
  ✓ OK » 51 honored (7.088s) 
  tests/heartbeat-test.js
·····················  
  ✓ OK » 21 honored (14.248s) 
  tests/i18n-tests.js
·················  
  ✓ OK » 17 honored (3.248s) 
  tests/idp-seen-test.js
············  
  ✓ OK » 12 honored (4.233s) 
  tests/internal-wsapi-test.js
······  
  ✓ OK » 6 honored (4.279s) 
  tests/jshint-test.js
··  
  ✓ OK » 2 honored (1.018s) 
  tests/list-emails-wsapi-test.js
············  
  ✓ OK » 12 honored (4.122s) 
  tests/logout-test.js
···········  
  ✓ OK » 11 honored (4.252s) 
  tests/metrics-header-test.js
·······  
  ✓ OK » 7 honored (3.332s) 
  tests/no-cookie-test.js
·······  
  ✓ OK » 7 honored (4.213s) 
  tests/page-requests-test.js
···static (36921): error: invalid url: /%e3h
···························  
  ✓ OK » 30 honored (3.446s) 
  tests/password-bcrypt-update-test.js
·················  
  ✓ OK » 16 honored (10.102s) 
  tests/password-length-test.js
··········  
  ✓ OK » 10 honored (4.122s) 
  tests/password-update-test.js
················  
  ✓ OK » 16 honored (8.278s) 
  tests/post-limiting-test.js
·········  
  ✓ OK » 9 honored (4.247s) 
  tests/primary-then-secondary-test.js
························  
  ✓ OK » 24 honored (7.280s) 
  tests/proxy-idp-test.js
··············  
  ✓ OK » 14 honored (5.209s) 
  tests/registration-status-wsapi-test.js
·······························  
  ✓ OK » 31 honored (5.271s) 
  tests/remove-email-test.js
··················  
  ✓ OK » 18 honored (4.091s) 
  tests/secrets-test.js
·····  
  ✓ OK » 5 honored (0.003s) 
  tests/session-context-test.js
··········  
  ✓ OK » 10 honored (4.138s) 
  tests/session-duration-test.js
······················  
  ✓ OK » 22 honored (5.263s) 
  tests/session-prolong-test.js
··········  
  ✓ OK » 10 honored (4.267s) 
  tests/simple-stage-user-utf8-password.js
···········  
  ✓ OK » 11 honored (4.269s) 
  tests/software-version-test.js
·  
  ✓ OK » 1 honored (0.003s) 
  tests/stalled-mysql-test.js
tests/static-resource-test.js
·  
  ✓ OK » 1 honored (0.004s) 
  tests/two-level-auth-test.js
···········  
  ✓ OK » 11 honored (3.647s) 
  tests/used-address-as-primary-test.js
··········  
  ✓ OK » 10 honored (4.064s) 
  tests/verifier-test.js
·······················································································  
  ✓ OK » 87 honored (7.230s) 
  tests/verify-in-different-browser-test.js
································  
  ✓ OK » 32 honored (7.245s) 
  tests/well-known-test.js
·······  
  ✓ OK » 7 honored (0.006s) 
  >>> Now Running: Front end unit tests under PhantomJS
· · · · router (37265): info: forwarding request: /common/js/error-messages.js -> http://127.0.0.1:10010/common/js/error-messages.js
currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
'waitFor()' finished in 44645ms.
Tests completed in 44455 milliseconds.
1451 tests of 1451 passed, 0 failed.
· · · ✓ OK » 7 honored (49.163s)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

If I run either `WHAT_TESTS=back npm test` or `WHAT_TESTS=front npm test`, everything passes as expected.

**Comment by lloyd** [comment]
@shane-tomlinson that's cause mysql isn't set up `Can't run tests: can't connect to the database`

**Comment by shane-tomlinson** [comment]
Imagine that @lloyd, I start up MySQL and things run as expected.

**Pull request merged**
