### PR TITLE
Make browserid work on Node 0.10

### PR DESCRIPTION
**Pull request by fmarier**
This is a combination of @lloyd's nodejs-0.10.0 branch as well as an update to the bundled lockdown script.

### CODE REVIEW

**Comment by jrgm** [comment]
If this is _the_ PR, you should update here - https://github.com/mozilla/browserid/blob/dev/.travis.yml#L11
so that this PR builds on travis with both 0.8 and 0.10. [1]

Note: Travis will lag 0.8.x and 0.10.x most recent by a week or so [2]

[1] http://about.travis-ci.org/docs/user/languages/javascript-with-nodejs/#Choosing-Node-versions-to-test-against
[2] http://about.travis-ci.org/docs/user/ci-environment/#How-travis-ci.org-VMs-are-provisioned

**Comment by arlolra** [comment]
@fmarier @jrgm you should quote the version in `.travis.yml`

as in, `- "0.10"`

also, in order to pass the tests,
https://travis-ci.org/arlolra/browserid/builds/6404330

you need to upgrade `client-sessions` to `0.1.1`
https://github.com/arlolra/browserid/commit/aca86a0cd5918ec3510231a06fb7347da2721982
(ignore the changes to the preinstall script)

**Comment by jrgm** [comment]
@arlolra - Thanks. Yeah, I was just about to mention that it should be a string.

**Comment by fmarier** [comment]
r-

While the tests look like they pass, authentication doesn't seem to work at the moment :(

**Comment by lloyd** [comment]
closing down this stale pull request, opening a new one.

**Pull request closed without merging**
