### PR TITLE
slightly delay shutdown of run_locally.js daemons to avoid shutdown races

### PR DESCRIPTION
**Pull request by jrgm**
Fixes https://github.com/mozilla/browserid/issues/3465

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@jrgm, do you know what the root cause of this is?

**Comment by shane-tomlinson** [comment]
@jrgm - doh, you outlined the root cause in the original issue. This works for me locally, 

I am wondering if there is a way to guarantee that /wsapi/authenticate_user has completely finished before shutting down. For environments like Travis CI where no performance is very hit and miss, will 50ms always be enough? Can we set a bit on res from resetFailedAuthCount that is checked before attempting to shut down?

@lloyd, any input here or is this approach enough?

**Comment by jrgm** [comment]
So the problem isn't that the webhead /wsapi/authenticate_user shuts down before it is finished. It's sort of the opposite. It's that authenticate_user responds to the test with OK, the test then tells the dbwriter and webhead (and router, etc.) to shutdown; if the dbwriter shuts down before the webhead, then the webhead's attempt to POST to 
/wsapi/reset_failed_auth_tries on the dbwriter gets a connection reset.

So there'd have to be some central coordination of "Is everybody ready to shutdown", but that doesn't seem to me like a direction to follow. Alternatively, I considered introduce a delay in each daemon (or actually in the shutdown.js that they all use to do cleanup at shutdown), but that also didn't seem to be the right thing. 

Is 50ms long enough? I can't be certain, but seems to work in my travis run. I really think the race is just a couple of milliseconds, but I could up the timeout to 100ms if you think I should.

**Comment by jaredhirsch** [comment]
@jrgm in the interest of gettin' shit done, how about I merge this in, and if the problem persists, we up the delay some more?

**Comment by jrgm** [comment]
@6a68 Sold!

**Pull request merged**
