### PR TITLE
always use a lowercase domain in address_info

### LINKED ISSUE #3728: persona user ID receives error message "Gmail.com is not responding"
ed at emrsoftware.com reported in [Bug 898851](https://bugzilla.mozilla.org/show_bug.cgi?id=898851):

User Agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET4.0C; .NET4.0E)

Steps to reproduce:

A current User tries to login to my website (golfgrudge.com) using Persona User Id  email address = "ARJ412@Gmail.com".

Actual results:

After hitting next button, the user immediately gets the response "Gmail.com is not responding. Please wait a few minutes and try again. "  This happens every time, and happens using IE, Chrome, FireFox, (every thing I've tried it on.)  This user has been logging in successfully for months.  I assume this has something to do with the Persona / GMAIL interaction that has been recently added to Persona.

Expected results:

Persona should have the user verify the email by typing in the password, and then successfully authenticating the user.

/cc @callahad

### PR DESCRIPTION
**Pull request by seanmonstar**
fixes #3728

### CODE REVIEW

**Comment by lloyd** [comment]
NOTE: this should be two pull requests targeting train in testing AND dev if we want to hotfix stage and roll on wed/thurs with train-2013.07.17

**Comment by seanmonstar** [comment]
I updated the commit to catch the other places this was used.

**Comment by jrgm** [comment]
@seanmonstar - can you add some appropriate tests to this PR against the dev branch?

**Comment by seanmonstar** [comment]
@jrgm yup, done!

**Comment by jaredhirsch** [comment]
tests are passing for me and travis. merging

**Pull request merged**
