### PR TITLE
Bump useragent version to support IE11. Fixes #3718.

### LINKED ISSUE #3718: upgrade 3rd-Eden/useragent when it gets support for IE11
@6a68 asked about this in https://github.com/3rd-Eden/useragent/issues/27, and the answer was basically "when IE11 is released". This bug is a reminder that we should update our version of useragent at that time.

### PR DESCRIPTION
**Pull request by jaredhirsch**
@jrgm Mind reviewing? Turns out @3rd-Eden fixed this long ago, see the [Changelog](https://github.com/3rd-Eden/useragent/blob/master/CHANGELOG.md) for 2.0.4.

### CODE REVIEW

**Comment by jaredhirsch** [comment]
@jrgm thanks for the heads up. test should be fixed.

**Comment by jrgm** [comment]
Works for me, in tests, or in real browser. Merging.

**Comment by jrgm** [comment]
I swear I tried 2.0.6 here https://github.com/mozilla/browserid/pull/3719#issuecomment-21596918 and didn't see it work, but it works now.

**Comment by 3rd-Eden** [comment]
That is correct, the 2.0.7 release fixed a bug in IE 11 parsing. It was targeting the previously known UA instead of the version they released in the beta's.

**Comment by jrgm** [comment]
Hey @3rd-Eden. Thanks for the clarification!

**Pull request merged**
