### PR TITLE
add nodejs 0.8 to travis-ci

### PR DESCRIPTION
**Pull request by seanmonstar**

### CODE REVIEW

**Comment by seanmonstar** [comment]
travis took it on like a champ. http://travis-ci.org/mozilla/browserid/builds/2054278

**Comment by shane-tomlinson** [comment]
@seanmonstar - Are there plans to upgrade everybody/servers to node 0.8.*? 

I'm nervous about setting Travis to use 0.8.0 if our ephemeral instances and servers are using v0.6.15.

**Comment by lloyd** [comment]
This tests both 0.6 and 0.8, it doesn't remove v0.6.

--lloyd

**Comment by lloyd** [comment]
:+1:

**Comment by ozten** [comment]
This is awesome!

Where in the schedule would this fall, roughly?

I don't think we want to upgrade node (if it isn't a hard dependency), until we've got confidence in our deployment systems.

**Comment by seanmonstar** [comment]
We want to upgrade eventually, since 0.8 is faster, has more secure TLS,
and many dependencies will begin to require it. However, right now we don't
need to.

This will just show that when we want to upgrade, it will be OK, because
tests pass.

**Comment by jrgm** [comment]
verified

**Pull request merged**
