### PR TITLE
Improve language in email when an IdP drops support AND improve password reset flow

### PR DESCRIPTION
**Pull request by lloyd**
I'm combining PR #2936 and PR #2961 

These address issue #1232 and issue #2937 

It sucks to conflate these two things, but because the first PR introduces a regression (makes it so that a user cannot use an email address if the provider disables), I don't think it can be merged independantly.

### CODE REVIEW

**Comment by lloyd** [comment]
@shane-tomlinson last known bug in this pile of patches happens when trying to run selenium tests which excercise the path when an IdP disables support.  

Concrete issue is that the dialog does not progress to waiting at the moment a user chooses their password.  Have a look at this video: https://saucelabs.com/tests/5138cdb6088f4df894914d0fe83d9058

look carefully at second 42 - the "done" button displays a spinner, then becomes clickable again and the dialog does not progress to a waiting page.  At second 50 you can see the dialog pop back to the foreground.

**Comment by jaredhirsch** [comment]
Grabbing this PR unless you have someone specific in mind to review it, @lloyd.

**Comment by lloyd** [comment]
I've already reviewed, as far as I'm concerned a final rerun of selenium tests and its ready for merge.

-- lloyd (thumb-typing)

**Comment by lloyd** [comment]
r- @shane-tomlinson pointed out today that we cannot rollback with this patch.

Strategy is to break out the UI changes that would cause the new password flow to take affect and only commit the new landing page and server apis.  This would allow us to merge the actual UI changes in a subsequent PR and roll them out with a rollback path.

**Comment by shane-tomlinson** [comment]
Closing in favor of #2995

**Pull request closed without merging**
