### PR TITLE
Node 0.8.x support

### PR DESCRIPTION
**Pull request by lloyd**
teensy patch, doesn't break 0.6, lets devs work with 0.8 if they want to and lets us start exploring it.  (really all this does is eliminate deprecation warnings)

### CODE REVIEW

**Comment by zaach** [comment]
+1

**Comment by lloyd** [comment]
@jedp notes that I overlooked the fact that 0.6 fs has no .existsSync - doh!  I swore I tested that!  he's taking the PR and will patch

so r-

**Comment by jedp** [comment]
Jeeeeesus!  Sorry about the rebase mess.  It seemed I needed some of those earlier updates.  But oi, sorry.

Here's my bit - just a wrapper for `existsSync`!  Commit 09f65ff

**Comment by lloyd** [comment]
r+ on jedp's update to this patch.  tested on 0.6 and 0.8 - no deprecation output on console from unit tests.

**Pull request merged**
