### PR TITLE
mitigate change in iOS7 privacy behavior - no longer logout users upon reload

### PR DESCRIPTION
**Pull request by lloyd**
Mitigation for issue #3905

if desired, we should hotfix this into stage or prod. /cc @callahad @6a68 @shane-tomlinson @jrgm 

deployed at http://ios7.123done.org

### CODE REVIEW

**Comment by callahad** [comment]
> if desired, we should hotfix this into stage or prod.

**We must hotfix this.** User's can't log into Persona-based sites on iOS. ([Video](http://www.youtube.com/watch?v=Yq4MPKJNpyo))

@jrgm What do you need to make hotfixing a possibility?

**Comment by jaredhirsch** [comment]
works on iOS 7 MobileSafari and Chrome: able to log into 123done, not logged out on reload.

i was concerned about how we are setting the storage check key (per IE8 worries mentioned elsewhere in the storage.js file), but can't repro any problems seen in #1637, so I think this is good to hotfix.

**Comment by jaredhirsch** [comment]
merging :beers:

**Comment by lloyd** [comment]
so @callahad - I'll leave it to you to work with @jrgm and delegate hotfixing / cherry picking this into an appropriate train, I'm out for now.

**Comment by jrgm** [comment]
We can take this in the delayed 09.11 branch, which I still have to get on stage.

**Comment by callahad** [comment]
This fix is now live in production

**Pull request merged**
