### PR TITLE
Constrain tooltips to be displayed on the screen.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@jedp and @jrgm - this is a hotfix to the current stage for #3496. An ephemeral instance exists to test, tooltips-off-screen-stage.personatest.org

### CODE REVIEW

**Comment by jaredhirsch** [comment]
@shane-tomlinson based on the screenshot in #3496, I wonder if tooltips will now obscure the fields they are supposed to point at?

**Comment by shane-tomlinson** [comment]
@6a68 - one tooltip will, but having the tooltip fully readable is better than off the screen. For more context, read https://github.com/mozilla/browserid/issues/3496#issuecomment-19258637. I am OK with the tooltip obscuring the field for this single case, especially since tooltips should be going away soon now that initial work has started for #3154.

**Comment by jaredhirsch** [comment]
@shane-tomlinson sounds good to me :-)

**Comment by jedp** [comment]
Looks good to me, too.  Having the tooltip obscure that field seems fine.  It's still very usable (much more so than before), and the tooltips are a short-term fix anyway.

@jrgm I've merged the corresponding pr into dev

**Pull request merged**
