### PR TITLE
add P3P headers to endpoints IE might care about

### PR DESCRIPTION
**Pull request by jaredhirsch**
Reopened. @shane-tomlinson or @lloyd, mind taking a look?

I split this off from the main blob of third-party cookie discussion.

Add P3P headers to IE family browsers (a little searching suggests IE9 and, presumably, IE10 also care about this header).

Do I need to add tests to confirm this header is appended if the user-agent header contains an IE-like string?

### CODE REVIEW

**Comment by jaredhirsch** [comment]
this should fix #2340

**Comment by jaredhirsch** [comment]
relevant MSDN page with some discussion of IE privacy policy:

http://msdn.microsoft.com/en-us/library/ms537343(v=vs.85).aspx#privacy_preference_settings

**Comment by jaredhirsch** [comment]
@lloyd @shane-tomlinson thoughts on this'n?

**Comment by shane-tomlinson** [comment]
@6a68 - I do not think this is needed anymore, esp with the 3rd party cookie changes in #3116. IE allows a 3rd party site to send cookies as soon as the user visits that site.

**Comment by jaredhirsch** [comment]
I'll test with an IE8 VM to see if this affects first-time user experience. If it doesn't, I'll close.

**Comment by jaredhirsch** [comment]
After rebasing against current dev, I can't produce any problems with first-time experience on IE8 or IE9. CLosing.

**Comment by jaredhirsch** [comment]
Reopening because #3417.

**Comment by jaredhirsch** [comment]
@TeeTeeHaa (affected user) confirms this patch fixes #3417

**Comment by shane-tomlinson** [comment]
@6a68 - lockdown seems to not like this change, see the travis logs.

**Comment by jaredhirsch** [comment]
@shane-tomlinson Fixed the lockdown error, working for me. Mind taking another look?

**Comment by jaredhirsch** [comment]
I can't figure out why the travis build failed. The tests run fine on my local machine and the failing tests aren't affected by my patch.

**Comment by jrgm** [comment]
There. I made you green.

**Comment by jaredhirsch** [comment]
thanks @jrgm!

somebody clicky!

**Pull request merged**
