### PR TITLE
generate_ephemeral_keys.js instead of .sh

### PR DESCRIPTION
**Pull request by seanmonstar**
making this script cross-platform

addresses a point in #1769

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Does the original .sh file need to be removed from the repo?

**Comment by seanmonstar** [comment]
I guess so. I'll add a commit removing it.

**Comment by shane-tomlinson** [comment]
@seanmonstar - When I run `npm install` a second time after the key is already generated, I get the following error:

```
[10:21][browserid(nodejs-ephemeral-keys)] $ npm install
npm WARN node-statsd@0.0.2 package.json: bugs['web'] should probably be bugs['url']
npm http GET https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
npm http 200 https://github.com/downloads/lloyd/node-statsd/0509f85.tgz

> browserid@0.0.1 postinstall /Users/stomlinson/development/browserid-jacked
> node ./scripts/generate_ephemeral_keys.js

*** Generating ephemeral keys used for testing ***

fs.js:373
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: EEXIST, file already exists '/Users/stomlinson/development/browserid-jacked/var'
    at Object.mkdirSync (fs.js:373:18)
    at /Users/stomlinson/development/browserid-jacked/scripts/generate_ephemeral_keys.js:40:6
    at /Users/stomlinson/development/browserid-jacked/scripts/generate_ephemeral_keys.js:13:13
    at ChildProcess.exithandler (child_process.js:280:7)
    at ChildProcess.emit (events.js:70:17)
    at maybeExit (child_process.js:360:16)
    at Process.onexit (child_process.js:396:5)
npm ERR! browserid@0.0.1 postinstall: `node ./scripts/generate_ephemeral_keys.js`
npm ERR! `sh "-c" "node ./scripts/generate_ephemeral_keys.js"` failed with 1
npm ERR! 
```

It looks like before creating the directory, its existence needs checked for.

**Comment by shane-tomlinson** [comment]
r+ with modification to check for directory existence before creation, found in #2146.  Nice change @seanmonstar - Developing on Windows is almost a reality!

**Pull request closed without merging**
