### PR TITLE
Update package.json metadata, fixes #3555

### LINKED ISSUE #3555: Add an npm repository field
When running my first `npm install`, I get a warning:

`npm WARN package.json browserid@1.0.0-b1 No repository field.`

### PR DESCRIPTION
**Pull request by callahad**

### CODE REVIEW

**Comment by seanmonstar** [comment]
Technically, we're at b2 now.

**Comment by shane-tomlinson** [comment]
@callahad, as @seanmonstar says, we are on b2 now. Wanna update that while you are digging in there?

**Comment by callahad** [comment]
Done

**Comment by jaredhirsch** [comment]
my head a splode :rainbow: :rainbow:

**Comment by callahad** [comment]
:boom: :exclamation:

**Pull request merged**
