### PR TITLE
Feeley email updates

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@ryanfeeley - I manually merged what I could from PR #3938 and then manually edited the rest. How is this looking for you?

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@ryanfeeley - the split line footer looks a bit off. Is this how you wanted it to look?

screen shot 2013-10-08 at 17 17 33

**Comment by ryanfeeley** [comment]
@shane-tomlinson Thanks for the preview Shane! You are right. I don't want a line-wrap in the context.

**Comment by shane-tomlinson** [comment]
The footer is a single line again:

screen shot 2013-10-09 at 10 53 31

**Comment by shane-tomlinson** [comment]
If the RP does not specify a siteName, the dialog shows "Sign in to with..."
screen shot 2013-10-09 at 11 13 04

**Comment by ryanfeeley** [comment]
Domain? Or drop the "to"? (will need i18n consideration)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I added the domain and merged.

**Pull request merged**
