### PR TITLE
Track include.js component versions

### PR DESCRIPTION
**Pull request by jaredhirsch**
Bump jschannel to latest version, and include jschannel and winchan git sha in the include.js local copy.

Running on an ephemeral instance, https://tracksha.personatest.org

### CODE REVIEW

**Comment by jaredhirsch** [comment]
gah! jshint errors.

**Comment by jaredhirsch** [comment]
derp. I messed something up toggling between branches. passes now.

**Comment by jaredhirsch** [comment]
force-pushed to catch xhr fixes from earlier this morning

**Comment by jaredhirsch** [comment]
I can't repro the travis failure locally.

**Comment by seanmonstar** [comment]
JSChannel looks like it went from 2-spaces to 4.

**Comment by jaredhirsch** [comment]
@seanmonstar yeah, I'm treating it as an upstream library and leaving it with 4-spaces. I'd like to not have it in the repo, and just pull it in as part of the build process, but didn't want to get into that here.

**Pull request merged**
