### PR TITLE
upgraded jwcrypto and start mixing in server-side entropy

### PR DESCRIPTION
**Pull request by benadida**

### CODE REVIEW

**Comment by jrgm** [comment]
I spun up an awsbox with this bugfix-better-randomness branch. With Android ICS and any of FF,FFBeta,Aurora,Nightly the main site lays out horribly, which is probably due to this error seen in 'adb logcat'. 

E/GeckoConsole( 4730): [JavaScript Error: "NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIDOMWindow.crypto]" {file: "https://jtrain0622.personatest.org/v/aee20dd813/production/en_US/browserid.js" line: 5}]

Note: For stock and Chrome Beta on ICS, I do not see this problem, and I don't see a problem with desktop XP or osx with FF and non-FF browsers, so my aws deploy doesn't appear to be the problem. Let me know if you need further info.

**Comment by jrgm** [comment]
I rechecked in a local dev instance; I see hints in bugzilla that Fennec does not yet implement window.crypto. The failing line in local dev is ./node_modules/jwcrypto/lib/rng.js:51

**Comment by lloyd** [comment]
@jrgm thanks for the advanced testing, @benadida - looks like this is an r- for now.  any way I can help?

**Comment by benadida** [comment]
@lloyd @jrgm updated jwcrypto to try/catch for silly browsers that throw an exception when you even touch window.crypto. Can you try this again on funky Fennec?

**Comment by jrgm** [comment]
I gave this a quick spin with the update better-... branch with the latest FF/FFBeta/Aurora/Nightly (now all non-XUL) and no errors for window.crypto on main site, so looks good to me.

**Comment by lloyd** [comment]
please rebase against latest dev

**Comment by benadida** [comment]
@lloyd your wish is my command! rebasing and re-testing done.

**Comment by lloyd** [comment]
tested, reviewed code, IE8 was broke, fixed, r+, merging.

**Comment by jrgm** [comment]
marking verified for stage train-2012.07.06

**Pull request merged**
