### PR TITLE
optimize backend unit tests by starting all daemons in parallel, and the...

### PR DESCRIPTION
**Pull request by lloyd**
...n starting router.  issue #1803

on my dual coare 13" mbp this reduces total runtime of backend tests from 8m51.564s to 7m10.813s - that's a 20% speedup for a very safe and isolated change in just the test harness.  This also decreases the time from typing `npm start` to actually being able to hit the local server.

review and merge at will, plz.

### CODE REVIEW

**Comment by zaach** [comment]
I noticed a small speed-up on a faster MBP, but looks good! r+

**Comment by lloyd** [comment]
zaach: what kinda speedup do you see? you gots 4 cores?

**Comment by zaach** [comment]
2.5 GHz Intel Core i7

It went from about 2m50s to 2m43s.

**Comment by lloyd** [comment]
i need a new computer!

**Comment by zaach** [comment]
Haha, +1

**Pull request merged**
