### PR TITLE
Remove duplicate winchan

### PR DESCRIPTION
**Pull request by fmarier**
This pull request depends on PR #3758.

/cc @jrgm

### CODE REVIEW

**Comment by jrgm** [comment]
`https://github.com/fmarier/browserid/commit/aa692aee0fd2257dfe6b7a1492c558b2aa6ca780?w=1` shows that aa692ae is a no-op.

**Comment by fmarier** [comment]
@jrgm pointed out that I forgot to minify the scripts before doing the size comparisons.

Including the whole winchan library increases the minified size of `include.js` by 870 bytes (262 bytes gzipped).

**Comment by jrgm** [comment]
Note for reviewers: don't even look at this until PR-3758 is merged, since these two PR's include some of the same commits.

**Comment by jaredhirsch** [comment]
@fmarier would you mind rebasing this set of changes against current dev, now that #3758 has been merged?

**Comment by fmarier** [comment]
I will rebase and re-push now.

@6a68 I moved the git hash to the commit log (see https://github.com/fmarier/browserid/commit/ac57ca5d4ae3b71d3fa68bdab37e408cd009c0c6). I figured that since it's one more thing to update after patching winchan, it may not always match reality. (For example, it is a lie on production right now because I applied a hotfix but didn't change the comment at the top of the file.) A wrong comment is usually worst than no comment :)

**Comment by jaredhirsch** [comment]
@fmarier thanks for updating! putting the sha in the commit log seems fine to me, and it's nice to be able to just diff files directly.

i'll have a look in a few.

**Comment by jaredhirsch** [comment]
whoops, forgot to click the green button. :beers:

**Pull request merged**
