### PR TITLE
Fix check_primary_support to read responses

### PR DESCRIPTION
**Pull request by robottaway**
Hi been working on implementing and IDP for my site, was using the check_primary_support script and found it was not reading the responses when checking for script tags in the provision and auth endpoints. May be worth taking a look at my fixes to make it work for me.

-rob

### CODE REVIEW

**Comment by jrgm** [comment]
Link to #3221

**Comment by callahad** [comment]
I should be able to review this.

**Comment by shane-tomlinson** [comment]
This change should also be merged into shane-tomlinson/checkmyidp.org

**Comment by jaredhirsch** [comment]
cc @callahad

**Comment by callahad** [comment]
r+, works as intended. Merging.

**Comment by callahad** [comment]
Thanks @robottaway ! Sorry for the delay in getting that in.

**Comment by robottaway** [comment]
@Dan notice you all have a few other things to do ;) Seems plenty fast
given that.

cheers
rob

**Pull request merged**
