### PR TITLE
Can't uncheck the persistence check box

### PR DESCRIPTION
**Pull request by ghost**
Adjust the CSS selector in pick_email.js to only match e-mail radio buttons

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Link to #1155 for tracking.

**Comment by shane-tomlinson** [comment]
@fawek - Awesome, thanks for the contribution here - esp the tests.

The original reason for using Javascript to select the radio buttons is because iOS does not select the radio buttons when clicking on the corresponding labels.  It looks like check boxes suffer from this as well.

Would it be possible for you to expand your pull request so that when clicks on the "Always sign in using this email" label are received, it toggles the checkbox on iOS?

Thanks again!

**Comment by ghost** [comment]
Thanks for the review! I can't test this on iOS but this should work.

**Comment by shane-tomlinson** [comment]
@fawek - Thanks for the update!  I did some cross browser/device testing and came up with some strangeness - namely, you can no longer click on the radio or checkbox itself with any effect.  Labels are all good.

I have added a bunch of unit tests and am going to have a deeper look tomorrow.

**Comment by shane-tomlinson** [comment]
@fawek - Thanks for this pull request.  I used a modified version of this request along with some additional tests for pull request 1163 - https://github.com/mozilla/browserid/pull/1163.

Thanks again!

**Comment by ghost** [comment]
@shane-tomlinson - Awesome, yours looks much cleaner!

**Pull request closed without merging**
