### PR TITLE
Committing work on behalf of Inma Barrios

### PR DESCRIPTION
**Pull request by ozten**
Spanish versions of TOS PP as a hotfix for train-2013.06.19

### CODE REVIEW

**Comment by ozten** [comment]
@jrgm - Is it okay to add this as a hotfix?

Reviewer: Please review and r+, but don't merge until QA agrees to accept this on train-2013.06.19

**Comment by jaredhirsch** [comment]
@ozten I'll review right now and try to test locally. Zerigo is still down, so I can't test on an ephemeral instance.

**Comment by ozten** [comment]
Awesome, thanks!

(I know Zerigo has blocked me all week :( )

**Comment by jaredhirsch** [comment]
@ozten @jrgm R+

This looks good to me, though I'm not sure I've tested everything. @ozten let me know if there's stuff I've missed. Here's what I've done (by the way, I couldn't find the l10n setup instructions anywhere in the repo/wiki, are they in the docs somewhere?):

#### setup
1. download the branch, rm -rf node_modules && npm install
2. svn co http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale
3. ./locale/compile-json.sh locale resources/static/i18n
4. CONFIG_FILES=config/l10n-all.json ./scripts/compress
5. add supported_languages block from config/l10n-all.json to config/local.json
6. npm start

#### stuff I verified
1. In FF, make Spanish [es] the #1 language
2. load localhost:10002
3. verify that the TOS and PP links in the dialog go to Spanish-translated embedded_tos and embedded_pp links
4. verify that the TOS and PP links onsite go to Spanish-translated TOS and PP links
5. Repeat for Polish (for the other bug)

**Comment by ozten** [comment]
jrgm said cool in IRC

**Pull request merged**
