### PR TITLE
Fix globals that were being unintentionally created in wsapi.js

### PR DESCRIPTION
**Pull request by zaach**
Some apparent copy/paste errors were causing global variables to be created in wsapi.js. This commit fixes the global creation and fixes modules that were relying on the implied globals.

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@zaach - On the surface, this PR looks great.  Unfortunately, I am getting errors while running ./scripts/test_backend.  Until the tests pass, r-.

```
[11:46][browserid(zaach_dev)] $ ./scripts/test_backend                          
tests/add-email-with-assertion-test.js
The "sys" module is now called "util". It should have a similar interface.
Setting NODE_ENV to test_json to test with the local JSON database
To test with a local mysql database, setup mysql and set NODE_ENV to test_mysql
······error getting csrf token:  http error
✗✗
```

**Comment by shane-tomlinson** [comment]
@zaach - When creating a new browserid directory and checking out a new branch with your changes, everything works as expected.  Digging deeper.

**Comment by shane-tomlinson** [comment]
After removing the locales directory, putting the computer to sleep and re-waking it, the tests all passed.  I was unable to reproduce the above problem and merged this in.  @ozten saw the same problem when he updated.

**Comment by jrgm** [comment]
verified in train-2012.06.08

**Pull request merged**
