### PR TITLE
declaritive api

### PR DESCRIPTION
**Pull request by seanmonstar**
**WIP**. Currently for discussion and code review purposes.

Still missing:
- [ ] POST from our /verify_email endpoint back to RP returnTO

### CODE REVIEW

**Comment by seanmonstar** [comment]
linking to #1946

**Comment by eevee** [comment]
whoa _awesome_.  thanks so much for doing this!  glad to see it's being well-received so far too  :)

**Comment by fmarier** [comment]
There's a lot of good stuff in here that has nothing to do with the declarative API (cleanups, jshints, etc.). Maybe we could split these things into a separate pull request and merge that one first?

**Comment by seanmonstar** [comment]
yea perhaps. i was just working in include.js, and getting annoyed how jshint would warn me on every save, so I fixed all the warnings :D

**Comment by eevee** [comment]
i'm pretty close to needing an auth system for a project; any indication whether this is likely to be adopted?  there was no opposition in the thread, at least  :)

**Comment by callahad** [comment]
Persona is in maintenance mode for the moment, as the Cloud Services group at Mozilla is heads-down on Firefox Accounts and a revision to Firefox Sync. I'd suggest going ahead with one of our existing APIs instead.

**Comment by jaredhirsch** [comment]
@seanmonstar it seems like the include.js portions of this have been pulled into a separate PR. Would you mind splitting that stuff out from this one?

Also, I hate to be that guy, but the spelling is **declarAtive**, would you mind fixing that throughout?

:beers:

**Comment by callahad** [comment]
I'm going to close this as wontfix for now. Even though I like the design, I don't think merging in a completely new API is in our best interest right now. :(

**Pull request closed without merging**
