### PR TITLE
Inline two images only used by the dialog

### PR DESCRIPTION
**Pull request by fmarier**

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
This is awesome, but causes very strange behavior in Chrome Beta for OSX that is not present when opening the dialog from dev.123done.org.

Screen Shot 2013-02-19 at 12 34 47

Screen Shot 2013-02-19 at 12 34 30

**Comment by shane-tomlinson** [comment]
The above behavior is visible in local dev as well, this PR does not change anything. Oddly enough, it goes away on ephemeral instances.

r+. Will merge as soon as given the green light.

**Comment by shane-tomlinson** [comment]
Wait, WAIT!

I re-pushed to an ephemeral instance to check out the performance and noticed that the compressor is failing on push:

```
remote:   errno: 34,
remote:   code: 'ENOENT',
remote:   path: '/home/app/code/resources/static/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGoAAAD5CAMAAAD4DVBIAAABSlBMVEXv8PL/v8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PLv8PK0tbbf4OK1trexsrTe3+Gys7W3uLixsrPCwsObnJ7x8vPk5eapqqzFxse5urvGxsesrKzn6On09favsLGdnZ7DxMXOzs/u7/DGyMnLy8zS09PExcaoqarw8fOam5vAwcKwsbO6u7y7vL2sra7T1NTKzM33+PjU1dbV1tfv8PHv8fLu8PHv8PKLr7NpAAAAQXRSTlMAAP4GDP0dKPpD/BJSc/fuM+eI+JxId5TpOGGn0YTv1q7d9OFlvsxX9fvEasm443zH66C08tmq1CMXAbuj7AjIgCcb4VYAAAN7SURBVHja3d3XUxNhGMXhZHs2PUBCSQgBRJEmNrB3wS5YQemoWM7/fyuDjBcLl5vf6Hvuws0zk8kws9++7/kycgqZbib7NxkpCjFKZQ+j1OYoXeUo1TnKyWGUogCjdMvFKDU5Sjc5SkWO8nMYpVKAUep3MUrTHKVejtI4R/kDGKVSHqNU5Sid5yg1OEqDHBVXMEqjeYzSGEfpBkepxlEqcFQcYpQuexilDkfpEkepxVFOAaMUhRilYQ+j1OYojXCU6hzl9GGUogCjVHYxSk2O0hBHqchRfg6j1BNglPpdjNI0R6mXozTOUf4ARqmUxyhVOUrnOUoNjtIgR8UVjNK5PEZpjKN0hqNU4yid5ag4xCiNehilDkdphqPU4iingFGaDDFKwx5Gqc1RGuEo1TnK6cMoRQFGqexilJocpSGOUpGj/BxGqSfAKPW7GKUJjlIvR2mKo/wBjFLpGkapylG6wFFqcJQGOcqvYJTO5TFKsxylMxylGkfpLEfFIUZp1MModThKMxylFkc5BYzSZIhRGvYwSlc4SiPdoH4mo6PMcZTTh1GKFjFKZRejtJCgupmhrlDP958+3X+uRIpdoO6/e7Gz8+Ldo8SfnVz61OPll6urL5cfnnx6TZ3a3/347NnH3X0lM++mTd3b25Q29x7oRCZSpt5uf97Y2tr4vP1WJ3IxPerHYVbWP7x+8uT1h/WVww9KZOp2mtTSpy9H+bR0CuXcuZ4itXtwnN3TqNk0qb3vx9k77Qv0silSrw7+SAevElS6P4tfh3m/9vUoa+8PPyR/7OlSb74d502SmnfTpJJJ/GOCKCeXpahilqKGshS1kKWosktR0WIWopy+DEXNZShqxOBDz7DHPaAafOxuGTwi6Rg8zopDg0ePNYPHxLMGj/T9isHXLw2Dr8qq4GtNgy9rpwy+WJ8AhyDsjXb4uX9yDOd/GS5qGhwEiwKDQ3t1gwOWbYPDsJOhwcHllsEh847BhYA4NLi8UTO4aDNmcCkqrhhcYGsYXDasgouhBtddxw2uJk8bXCPvCQyu/BcN1jM07VVpKAoM1p7UDVbUtA3WCUWhweqnlsGaro7BSrU4NFh/VzNYVThmsFYyrhisAG0YrGutgtW6BguDxw2WO08bLOIuBQZL04sGC+6bBi8jiAKDF0fU/4dLPv7Zq0vKnrVrZtDLc+5mIOo3f6TA3sIzTYgAAAAASUVORK5CYII=',
remote:   syscall: 'open' }
```

The portion of compress that replaces urls in the CSS with their cachified URLs does not know how to handle this. Can you update compress-worker.js to take care of this?

**Comment by fmarier** [comment]
oops! I should have tested that. I'll look into it today.

**Comment by shane-tomlinson** [comment]
Manually merging with the fix for the data: URI issue. See commit 79776d72466faa4ce334caf1726796b143a09ddc

**Pull request merged**
