### PR TITLE
repair internal.get API - it should return a bare assertion represented ...

### PR DESCRIPTION
**Pull request by lloyd**
...as a string, not an object - issue #1395

### CODE REVIEW

**Comment by lloyd** [comment]
@st3fan - can you please verify that this fixes the internal API for you.  Just...

... replace browserid.org with `issue1395.hacksign.in` for both where you include javascript resources and where you send assertions for verification.

depending on your report, we'll merge this or not.

**Comment by st3fan** [comment]
@lloyd I cannot test this on iOS from a UIWebView because iOS complains about the certificate for *.hacksign.in. Maybe the intermediate certificate is missing on your server?

**Comment by lloyd** [comment]
@st3fan try again please?  I _think_ I fixed the SSL issue.

**Comment by benadida** [comment]
on code alone, assuming @st3fan confirms, r+.

**Comment by shane-tomlinson** [comment]
@lloyd - When the old API is officially completely removed, we should clean up the unit tests for the internal api, there are a lot of tests with the "silent: true" option.

**Comment by st3fan** [comment]
@lloyd I tested against `issue1395.hacksign.in` and that works ok.

**Comment by lloyd** [comment]
given @benadida's review, and @st3fan's confirmation, I'm merging this.

**Pull request merged**
