### PR TITLE
Fixes #3573 : make sure the '.buttonrow > .right' buttons line up on the right hand side

### LINKED ISSUE #3573: Next button on authentication page is not lined up with the right hand side of the input box.
screen shot 2013-06-24 at 12 51 58

### PR DESCRIPTION
**Pull request by chilts**
Patch for #3573.

Hoping that this doesn't affect anything else.

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@chilts - I didn't get a chance to review this today, I'll have a look at it tomorrow!

**Comment by shane-tomlinson** [comment]
@chilts - unfortunately, that removes the margin when there is a button on the right and an anchor on the left (see set password or add email screens for an example). I forget the repercussions of just removing the right class from that button. Perhaps the "right" class on that button is just a relic of a past time and can safely be removed?

**Comment by chilts** [comment]
@shane-tomlinson ok, I'll re-look into this. I tried a number of different pages but must have missed that one. Thanks. :)

**Comment by shane-tomlinson** [comment]
@chilts - I'm gonna close this until we have a better solution. Want to pow wow on this? Thanks man!

**Comment by chilts** [comment]
@shane-tomlinson thanks for reviewing and pulling :)

**Pull request merged**
