### PR TITLE
Add building status to README file

### PR DESCRIPTION
**Pull request by juanpaucar**
Currently the README file is not showing any information about the building status, although i may seen not important i think it's good to keep track on what's going on with the repo, so i added the building status for the "future" branch, but could be changed to other branch if needed

### CODE REVIEW

**Comment by juanpaucar** [comment]
Fox example we could have noticed before that the build was failing for the main branch, future branch

seleccion_166

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Comment by callahad** [comment]
Whoops, the mass-closing script misfired. This is an awesome patch, thanks @juanpaucar! Merging now.

**Comment by juanpaucar** [comment]
You are welcome @callahad , i'm working to check what happened and why is the build failing too. i'd be really happy to help on somthing else

**Comment by callahad** [comment]
The build failure is issue #4179

There was a bug / regression in Node 0.10.30 that caused this issue. It was supposedly fixed on Node 0.10.31, but we're still seeing it on Travis with 0.10.33. :(

If you can reproduce the error on your own computer, that would be really awesome news.

**Pull request merged**
