### PR TITLE
Use Feura Sans font for the mobile layout.

### LINKED ISSUE #3430: [b2g] B2G apps use Feura Sans font set, not Open Sans

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@skinny97214, @mhanratty, I have updated the dialog available from http://all-together-now.123done.org to use the Feura Sans font set available from the https://github.com/mozilla-b2g/gaia/ repo. Can you see what you think?

fixes #3430

### CODE REVIEW

**Comment by jedp** [comment]
Holding off; @skinny97214 says no go on Feura

**Comment by skinny97214** [comment]
Just to clarify, hold until Maureen says go.

**Comment by shane-tomlinson** [comment]
Holding.

**Comment by jedp** [comment]
In Issue #3430, @mhanratty confirms that we do want to use Feura Sans on gaia

**Pull request merged**
