### PR TITLE
Support non-ascii passwords: when forwarding requests, Content-Length sh...

### PR DESCRIPTION
**Pull request by lloyd**
...ould be byte length, not number of unicode chars.  issue #1631

### CODE REVIEW

**Comment by jrgm** [comment]
I think you should add the same fix here: https://github.com/mozilla/browserid/blob/dev/lib/wsapi_client.js#L129-133
(I was writing a test for this, and I needed that (or alternatively, not setting content-length at all)).

**Comment by lloyd** [comment]
There are two interesting things here.  YES we need tests, and yes that fix needs to be here too.

Are you writing unit tests now?  That's freaking fantastic if so, but I'm also willing to take the responsibility for this one.

Either way, I'll add the fix now.

**Comment by jrgm** [comment]
Started looking more at the unit tests that are there, yes. I have a simple one for this flow (first ascii password, then same with a password in Russian), but if you want to do that test that's fine too.

**Comment by lloyd** [comment]
how about this, check in the simple test you've got in a branch, I'll review and append to this PR?

**Comment by lloyd** [comment]
@shane-tomlinson this thing is ready for review and merge at your leisure.

**Pull request merged**
