### PR TITLE
Issue 3715

### PR DESCRIPTION
**Pull request by pdehaan**

### CODE REVIEW

**Comment by jaredhirsch** [comment]
@pdehaan Thanks for submitting! Can you please rebase this branch against dev? I see your CSS fix in the list of commits for the pull request (8198b62).

**Comment by jaredhirsch** [comment]
@pdehaan FYI, this would have linked to #3715 if you'd said "fix|fixed|fixes #3715". See [this help page](https://help.github.com/articles/closing-issues-via-commit-messages) for more :-)

**Comment by jaredhirsch** [comment]
I'm not sure we want to add the MPL to the subparts of _include.js. @shane-tomlinson thoughts?

**Comment by shane-tomlinson** [comment]
Link to #3800 about removing the duplicate JSChannel.

@6a68 - as odd as it is, as outlined in the [MPL 2.0 FAQ](http://www.mozilla.org/MPL/2.0/FAQ.html#apply), I think we are required to have it on every file.

**Pull request merged**
