### PR TITLE
use awsbox at latest revision 

### PR DESCRIPTION
**Pull request by jrgm**

### CODE REVIEW

**Comment by jaredhirsch** [comment]
What if we instead rev the awsbox version number and just update package.json to use that?

**Comment by jrgm** [comment]
> What if we instead rev the awsbox version number and just update package.json to use that?

Not sure if we currently have to keys to publish a new module to npm, so I just want to cut out the middleman (npm). (And actually, I meant that to be at master; updated PR).

**Comment by jaredhirsch** [comment]
Well, it doesn't affect production, so I guess not pinning versions (using master vs a particular sha) is fine. Merging.

**Comment by jaredhirsch** [comment]
whoops. kicked travis, will check again later

**Comment by jaredhirsch** [comment]
but r+ from me, feel free to merge when it's green @jrgm

**Comment by seanmonstar** [comment]
The only maintainer of [awsbox on npm](https://www.npmjs.org/package/awsbox) is @lloyd !

**Comment by jrgm** [comment]
It's green.

**Pull request merged**
