### PR TITLE
KPI testing: added interaction_data activity to load_gen

### PR DESCRIPTION
**Pull request by kparlante**
Perhaps don't merge this just yet, but first attempt at adding capability for load testing kpi data push

### CODE REVIEW

**Comment by jrgm** [comment]
Hey @kparlante, thanks for doing this. Some comments:
- Instead of a hard-coded value for interaction_data.probability, maybe tie that to some proportion of the number of signin activities planned.
- maybe also check that the JSON from /wsapi/interaction_data is `{success: true}`.
- could someday also follow the pattern in other activities to pick a user (`userdb.getExistingUser()`), wrap cb, pick a context that may already have state, release user etc. But skip this point for this PR.

**Comment by kparlante** [comment]
Good points @jrgm, I've cleaned this up. 

Perhaps this shouldn't be a separate activity but instead a function in common.js. We could then add it to all relevant activities (which is I think everything but include_only.js), configurable by rate.

**Comment by jrgm** [comment]
@kparlante thanks for the update and looks good to me.

On the question of making interaction_data just something that happens on any activity that brings up the dialog just does, I'd thought about that. But signin in real world should be expected to dominate signup, reset_pass, change_pass, etc. So just tying this to signin seems fine to me (but did you mean `0.9`, not `0.8`).

Anyways, this tool could use an audit of which wsapi calls are made for each activity, as things have changed. But topic for another day.

**Comment by shane-tomlinson** [comment]
I am not sure how to run load_gen correctly. I set up an instance and tried to point load_gen at it, but I get 400 response codes. 

I have read docs/LOAD_GENERATION.md, but it is not giving me anything obvious. Is there a configuration option that I have to flip on?

**Comment by kparlante** [comment]
@jrgm: The logic for using 9 / 40 instead of 8 / 40 was that it should happen about as often as everything-that-is-not-include_only, or 100% - include_only. Or we could tie it to signin, agreed. If the tool gets an audit/overhaul, sure move it to be part of the other activities.
@shane-tomlinson: yeah, I'm not sure if it would be better to use the config for the sample rate or make it configurable from load_gen options -- one or the other is probably preferable to tweaking load_gen

**Comment by shane-tomlinson** [comment]
I am not sure what number I can go up to, when I peg it at 500000 users on a c1.medium instance, I start to see:

```
4rh 235sn 0iy 1cs)        (6 503s)
error: (signin) unknown: Error: connect EMFILE
error: (signin) unknown: Error: connect EMFILE
error: (signin) unknown: Error: connect EMFILE
error: (signin) unknown: Error: connect EMFILE
error: (signin) unknown: Error: connect EMFILE
error: (signin) unknown: Error: connect EMFILE
error: (signin) unknown: Error: connect EMFILE
error: (signin) unknown: Error: connect EMFILE
error: (signin) unknown: Error: connect EMFILE
error: (signin) unknown: Error: getaddrinfo ENOENT
[1241ms] 367567.20   395222.47   396398.77   212 R, 232 S (3sp 3rs 0al 5rh 199sn 0iy 2cs)    (10 ERRORS!)     (67 503s)
[1501ms] 407831.76   397744.32   396970.42   
```

This is intermittent, but somewhere is running out of file descriptors. I am unsure if this is on my local system or if this is reported from the remote end.

**Comment by jrgm** [comment]
Shane's issue is that osx has max files 250 by default, and I could easily see that being transiently surpassed during a run.

**Comment by jrgm** [comment]
Also re: size, I run tests @250K and add more instances to drive up to millions. The reason is that the number of users grows over time and at a certain point a single client core can't stay on schedule.

**Comment by jrgm** [comment]
verified in stage (sort of; see GH-3064, since in stage the current config leads to a bit of a loopback).

Hey @kparlante is there a test instance of the collector that we can file a ticket to get stage pointed at for initial load testing.

**Comment by kparlante** [comment]
@jrgm: I have two test instances of the collector right now (kpiggybank): kpiggybank-stage.personatest.org and kpiggybank-secure.personatest.org. Anyone can use kpiggybank-stage, access to kpiggybank-secure is whitelisted. Stage should point at the latter collector, and I'll need to configure it properly. Setting up stage properly also involves configuring the proxy, assuming it matches production. Details in #2831

**Comment by jrgm** [comment]
@kparlante - thanks for the info. Can we chat in IRC about stuff that needs to be done to finish stage in scl2 to point at https://kpiggybank-stage.personatest.org?

**Pull request merged**
