### PR TITLE
Adding dev_bid and default_bid which have millisecond resolution.

### PR DESCRIPTION
**Pull request by ozten**
Fixes Issue #1254 and Issue #1255

### CODE REVIEW

**Comment by ozten** [comment]
Also @jrgm if you could review, that would be great!

**Comment by jrgm** [comment]
So a couple of things:
- default_bid is missing the addition of :response-time
- I know the comments in connect show ':response-time ms' but the 'ms' seems to me unneccessary
- Do we actually have parsers that are digesting that timestamp? Would they not be fine with .toISOString() which includes the milliseconds as part of it?
- I think you meant .slice(-3), not .slice(-4)

**Comment by ozten** [comment]
I assumed metrics was using these logs (so it might break them?). ISO String lacks a time zone, which is probably fine. I'll make all these changes, thanks for the review!

**Comment by lloyd** [comment]
So looking at production formatted logs, there are two types of messages that make it in.  First we've got webserver logging:

```
{"level":"info","message":"127.0.0.1 - - [Mon, 12 Mar 2012 17:07:18 GMT] \"GET /ver.txt HTTP/1.0\" 200 86 \"-\" \"-\"","timestamp":"12 Mar 17:07:18"}
```

next, we've got programmatic logging:

```
{"level":"debug","message":"connecting to database: browserid","timestamp":"10 Mar 01:59:21"}
```

Rather than adding the millisecond resolution timestamp to the contents of the log message (which only is present in the former, how about we remove the date from the logging string the webserver emits, and change the timestamp present in all messages to include ms?

**Comment by lloyd** [comment]
How about this: 

```
--- a/lib/logging.js
+++ b/lib/logging.js
@@ -37,7 +37,7 @@ var filename = path.join(log_path, configuration.get('process_type') + ".log");

 exports.logger = new (winston.Logger)({
   transports: [new (winston.transports.File)({
-    timestamp: true,
+    timestamp: function() { return (new Date()).toISOString(); },
     filename: filename,
     colorize: true,
```

**Comment by ozten** [comment]
Putting all the feedback together
- Switch to now for timestamp
- Switch timestamp gobally

**Comment by ozten** [comment]
- Removed date-millis, we're good with the global update.

**Comment by jrgm** [comment]
verified on stage train-2012-03-14

**Pull request merged**
