### PR TITLE
Issue 900 main site dialog

### LINKED ISSUE #900: Consider changing "sign in" screen on main site to use dialog.
Referencing #383.  I think that the BrowserID main site should act as an RP and use the dialog to sign in, ditching the sign in screen.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Use the dialog for _ALL_ signin/signup, even from the main site.

fixes #900

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
I call bullshit on GitHub's "We can't automatically merge this pull request.", I just merged locally without a problem.

**Comment by callahad** [comment]
Are you serious? 83 additions and 942 deletions? This is amazing! Is it ready for review?

**Comment by shane-tomlinson** [comment]
Added a commit that @skinny97214 and I worked on separately that removes the "Sign up" button from the main site. This fixes the broken "Sign Up" button link.

Also fixes #3189

**Comment by jaredhirsch** [comment]
R+

Selenium and unit tests are passing for me.

Primary and secondary logins work in mac/Chrome, mac/FF 20, mac/Safari, Android 2.2 stock browser. Primary login not working in IE8, but that's a regression not introduced by this patch (busted in dev :-).

The patch looks fine, if borderline overwhelmingly large :-)

**Pull request merged**
