### PR TITLE
Qunit update

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Reissue of #3836 fixing all the things.

@jrgm - wanna run through this?

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Now, why is Phantom failing when Firefox isn't.

**Comment by jrgm** [comment]
Oh, haha. The new QUnit updates #qunit-testresult with the currently running test name. Our phantom runner was just polling for the string 'completed' in that innerText. So any test name with 'completed' would stop the test, and then we'd fail the test since it had no '\d+ failed' string ;-)

I looked at using the official runner addon from qunit, but it wasn't working, so I'll just make the pattern match a bit more specific on what stops the test (for now).

**Comment by jrgm** [comment]
Okay, this passes on travis/phantom now, as well as with FF 23, Chrome 28, IE{8,9,10}, Opera 12, Safari 6 run via Saucelabs. (modulo known test failures in IE9 and IE8 -- GH-3779 -- which are independent of this update).

**Comment by shane-tomlinson** [comment]
@jrgm - Man, I spent an hour and a half looking in the wrong direction yesterday w.r.t. the last commit to search for test failures.

**Pull request merged**
