### PR TITLE
persona_server tests added to run.py and run_saucelabs

### PR DESCRIPTION
**Pull request by klrmn**
extra bonus test fix

### CODE REVIEW

**Comment by jaredhirsch** [comment]
Unlike the huge patch with all the tests in it, which seemed a shame to wait a long while for merging in, I'm inclined to not flip the switch to activate the personaorg tests until the existing tests are rock-solid in Jenkins.

I'm working on Jenkins config today, so hopefully this won't sit for long.

**Comment by shane-tomlinson** [comment]
@6a68 - I'm gonna assign this to you to merge at your leisure.

**Comment by jaredhirsch** [comment]
@shane-tomlinson - cool, sounds good.

@klrmn - haven't forgotten about this. Jenkins work is nearly done, but stabilization isn't quite; hoping to merge in by early next week.

**Comment by jaredhirsch** [comment]
@klrmn - just to update the ticket - going to wait on this until beta is out, haven't forgotten about it

**Comment by jaredhirsch** [comment]
we're moving from python selenium to node selenium; closing accordingly.

**Pull request closed without merging**
