### PR TITLE
ToS: clarify that use in education and government is generally ok

### PR DESCRIPTION
**Pull request by fmarier**
This update to the terms of service comes from Jishnu Menon.

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@jedp, @ozten - what repercussions will this have for the effort the translate the TOS/PP for FirefoxOS?

Otherwise, I am r+, this is a great change, thanks for pushing @fmarier

**Comment by fmarier** [comment]
@shane-tomlinson Jishnu said that he should have the Polish and Spanish translations for us soon (with this change included).

**Comment by shane-tomlinson** [comment]
Awesome. Merging.

**Comment by callahad** [comment]
@fmarier Is there a bugzilla link or something from Jishnu that we can reference?

**Comment by ozten** [comment]
Unknown, let's not block on that. Go for it.

**Comment by ozten** [comment]
@callahad - The TOS/PP is a private legal bug. I've CC'd you.

**Pull request merged**
