### PR TITLE
Underscore props are filtered out of b2g identity messages, alas

### PR DESCRIPTION
**Pull request by jedp**
Fixes issue #3369

### CODE REVIEW

**Comment by seanmonstar** [comment]
I imagine this comes from the 1-line patch for B2G that got a giant pile up in Bugzilla... but also, for some reason the lack of _ is scarier. Probably a stupid conception on my part, as the "experimental" prefix should scare away everyone else.

**Comment by jaredhirsch** [comment]
wait, so does this mean I need to watch github during work week?! ;-)

**Comment by shane-tomlinson** [comment]
@jedp - can you update the parameters list in example/rp/index.html as well?

**Comment by shane-tomlinson** [comment]
@6a68 - Of course!

**Comment by jedp** [comment]
@seanmonstar this is not actually that issue in b2g, but yeah, there is platform code that's already filtering underscore properties out of the dom caller's message before sending it through gecko.  I want to rework the way we do that, but it won't be in this run, unfortunately.

**Comment by lloyd** [comment]
r+ given that @shane-tomlinson 's comments were addressed.

**Pull request merged**
