### PR TITLE
Fixes #4179. tests/stalled-mysql-test.js failing.

### LINKED ISSUE #4179: NODE_ENV=test_mysql node tests/stalled-mysql-test.js failing with Travis(0.10.31) and anything(0.10.30)
See: https://travis-ci.org/mozilla/persona/jobs/32913897

and

[12:56:37] travis-ci: [travis-ci] mozilla/persona#4291 (dev - e1e7f30 : Dan Callahan): The build failed.
[12:56:37] travis-ci: [travis-ci] Change view : https://github.com/mozilla/persona/compare/08e221291fbe...e1e7f3062619
[12:56:37] travis-ci: [travis-ci] Build details : http://travis-ci.org/mozilla/persona/builds/32913895
[13:40:33] callahad:  jrgm: By the way, node 0.10.31 should fixes the stalled-mysql-test.js failures. https://github.com/joyent/node/commit/6f043940bdcbfb5272be8ae959cd74b9fb5cf4f8
[13:41:11] callahad:  Not sure why that test run still fails
[13:41:55] callahad:  re-runs locally
[13:42:59] jrgm:      callahad: yeah, I had tracked down that same commit. But 0.10.31 didn't seem to fix it for me on linux.
[13:44:27] jrgm:      callahad: I was just about to file an issue to track, but then it passed with 0.10.31 on osx for me
[13:47:39] callahad:  jrgm: Hrm. That whole test run passes on OS X for me, too
[13:48:03] jrgm:      callahad: ... and now it passes for me on linux. So why fail on Travis with 0.10.31? (blah, blah, clocks, blah, blah, multi-tenant, blah, blah, ubuntu, ..)
[13:48:54] callahad:  goes to build 10.31 on Debian

### PR DESCRIPTION
**Pull request by abendigo**
Bump up the version of the temp module.

### CODE REVIEW

**Comment by callahad** [comment]
Could you please run `./node_modules/.bin/lockdown-relock` to regenerate the lockdown.json? Otherwise, Lockdown will be sad.

**Comment by abendigo** [comment]
When I run that, it make a lot more changes than I am expecting to lockdown.json

**Comment by callahad** [comment]
Huh, so it does. It shouldn't.

Let me try this locally...

**Comment by callahad** [comment]
I'll be damned. Works here. Works on Travis. I'll relock and manually merge.

I'm facepalming so hard right now -- saw the regression in Node 0.10.30 and it completely blinded me to other possible causes. THANK YOU! :beers:

**Comment by abendigo** [comment]
No worries. I am hoping this wont be my only contribution to this project.

**Comment by callahad** [comment]
Likewise :) I'm going to close this and merge in #4205, which includes a working relock.

I have to drop offline for a bit, but I'll merge as soon as I get back.

Normally I'd be curious about why your lockdown wasn't hashing things on relock, but instead, I'd like to just move to NPM's built-in shrinkwrap (#4184).

If you want to do more NPM plumbing work, that could be good :)

**Pull request closed without merging**
