### PR TITLE
Add the background image to the authentication email input.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@jedp - one more for you mang!
- Update the border of the input boxes to match the mocks.

ephemeral instance: email-input-bg.personatest.org

issue #3410

### CODE REVIEW

**Comment by jedp** [comment]
Oh nice!  you madman.  Testing now.

**Comment by jedp** [comment]
This seems to re-introduce the keyboard flicker.  I assume that's just because it's branched off an earlier version.

**Comment by shane-tomlinson** [comment]
@jedp - it does, I'll rebase and test.

**Comment by jedp** [comment]
Beautiful.

**Pull request merged**
