### PR TITLE
If the user hits the /signin or /forgot pages while signed in, redirect them to the "/" page.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
issue #1345

Things to check with this pull request:
- Make sure an authenticated user can still access /about, /privacy, /tos, and /
- Make sure a user with cookies turned off can still access /about, /privacy, /tos, and /
- Make sure a user with javascript turned off can still view /about, /privacy, /tos, and /
- Make sure an authenticated user is redirected to / when going to the /signin or /forgot pages.

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
This pull request makes much more sense when looked at with the w=1 GET option:

https://github.com/mozilla/browserid/pull/2178/files?w=1

**Comment by seanmonstar** [comment]
What do you think of a test case for this?

**Comment by shane-tomlinson** [comment]
@seanmonstar - I want to add unit tests for this module, but without a refactor, there is no way to load the module multiple times.

**Comment by seanmonstar** [comment]
Oh OK, fair enough. I hadn't noticed that the module was such an
anti-social singleton.

r+

**Comment by jrgm** [comment]
verified train-2012.08.17

**Pull request merged**
