### PR TITLE
support node 0.10.x

### PR DESCRIPTION
**Pull request by lloyd**
if travis agrees, this is ready for merge.

### CODE REVIEW

**Comment by lloyd** [comment]
r+ from me (but I don't count).  r+ from travis.  r+ from arch linux. r+ from osx.  everybody :heart: this thing.

**Comment by lloyd** [comment]
/me :fist: pumps, :dancers:, :cocktail:, :beers:, :checkered_flag:

**Comment by lloyd** [comment]
and whoever hits the green button gets a :banana:

**Comment by jaredhirsch** [comment]
:surfer:

Tests completed in 51673 milliseconds.
1725 tests of 1725 passed, 0 failed.

**Pull request merged**
