### PR TITLE
upgrade connect-cachify to 0.0.11

### LINKED ISSUE #2563: Update connect-cachify with globals removed
Globals have been removed from [connect-cachify](https://github.com/mozilla/connect-cachify) in master, so we should publish a new version in npm and get that merged into browserid.

@ozten can you, or do other people have authority to do that also?

### PR DESCRIPTION
**Pull request by seanmonstar**
removes globals variables 

fixes #2563

### CODE REVIEW

**Comment by ozten** [comment]
Travis is red, I'll check out your branch and have a looksy.
https://travis-ci.org/#!/seanmonstar/browserid/jobs/2729028

**Comment by ozten** [comment]
Hmm, looks like requesting :10002/ after installing 0.0.11 is busted.

```
ReferenceError: /home/ozten/browserid/resources/views/index.ejs:8
    6|       <div id="vAlign">
    7|           <div id="signUp">
 >> 8|               <div id="card"><img src="<%- cachify('/pages/i/slit.png') %>"></div>
    9| 
    10|               <h1 class="white headline-main"><%- gettext('Connect with Mozilla Persona, the safest &amp; easiest way to sign in.') %></h1>
    11|               <p class="tour white">

cachify is not defined
    at Object.<anonymous> (eval at <anonymous> (/home/ozten/browserid/node_modules/ejs/lib/ejs.js:234:12))
    at Object.<anonymous> (/home/ozten/browserid/node_modules/ejs/lib/ejs.js:239:15)
    at ServerResponse._render (/home/ozten/browserid/node_modules/express/lib/view.js:422:21)
    at ServerResponse.render (/home/ozten/browserid/node_modules/express/lib/view.js:315:17)
    at renderCachableView (/home/ozten/browserid/lib/static/views.js:62:7)
    at /home/ozten/browserid/lib/static/views.js:150:5
    at callbacks (/home/ozten/browserid/node_modules/express/lib/router/index.js:272:11)
    at param (/home/ozten/browserid/node_modules/express/lib/router/index.js:246:11)
    at pass (/home/ozten/browserid/node_modules/express/lib/router/index.js:253:5)
    at Router._dispatch (/home/ozten/browserid/node_modules/express/lib/router/index.js:280:4)
```

npm test on that project is green, but I must have hozed something...

**Comment by seanmonstar** [comment]
Hmm, doesn't this line make that available? https://github.com/mozilla/connect-cachify/blob/master/lib/connect-cachify.js#L55

**Comment by ozten** [comment]
I see the view executing before setup is run, so res.local('cachify') is undefined when the template is evaluated.

This PR swaps when we run the templates.
https://github.com/seanmonstar/browserid/pull/7

**Comment by seanmonstar** [comment]
Oh, I see. Good catch.

**Pull request merged**
