### PR TITLE
Remove no op code from email

### PR DESCRIPTION
**Pull request by ozten**
I don't believe the `_` function does anything here.

This removes this no op codepath.

### CODE REVIEW

**Comment by jaredhirsch** [comment]
@ozten I see the same noop function in lib/static/views. Is this a relic from how we used to do i18n? Are the two cases different?

**Comment by jaredhirsch** [comment]
@ozten for more context, looks like the gettext underbar noop was added to lib/email in commit 5a28b8f, and to lib/static/views in e90869ce.

**Comment by lloyd** [comment]
how will l10n code extract these strings?

**Comment by ozten** [comment]
With gettext used in the .ejs template files.

**Comment by lloyd** [comment]
@ozten - I don't understand, I'm sorry.  The only place I see the string 'Confirm email address for Persona' decorated in a way that l10n will extract it is in `lib/email.js`.  I grepped even!

So how will string extraction pick up this string if we remove the decoration?

**Comment by ozten** [comment]
Great catch @lloyd!

Interesting. I forgot that `scripts/extract_po.sh` adds `_` as a keyword alias for gettext.

This is fine. The _only_ places we use the `_` alias is lib/email.js and lib/views.js (at least as far as I had poked around). This is potentially problematic.

Recommendations: 
- Use `_` more widely or 
- comment the link to Gettext wherever we declare `_` or 
- change `_` to  `___` or 
- use only `gettext` throughout email.js.

History: In many webapps we use `_` exclusively for Gettext. With Persona, we didn't want to use that as we used the underscore library liberally in the front and backend. So this support was baked into extract_po.sh but I completely forgot about it. If matjazz used our new i18n-abide based tools, they wouldn't have extracted these strings. Being emails, it probably would have taken a while for a localization bug to be filed.

Closing this pull request, as it isn't the right fix.

**Comment by ozten** [comment]
Filed https://github.com/mozilla/i18n-abide/issues/26

**Comment by lloyd** [comment]
+1 to s/_/gettext/ - the underbar is too sneaky.

**Pull request closed without merging**
