### PR TITLE
update vows and wd versions

### PR DESCRIPTION
**Pull request by edwindotcom**
this fixed https://github.com/mozilla/persona/issues/4167 on my mac.

### CODE REVIEW

**Comment by pdehaan** [comment]
~~If ye change the package.json, do ye need to change the lockdown.json as well?~~
Nevermind, I just saw that this wasn't the main package.json, but is in a non-lockdown-ed subdir.

**Comment by edwindotcom** [comment]
@pdehaan out of dumb luck - the root lockdown file has vows defined:
https://github.com/mozilla/persona/blob/dev/lockdown.json#L486

and wd was never lockeddown anywhere

**Comment by edwindotcom** [comment]
I ran this with dev and current train branch and tests were able to run.

**Comment by karlht** [comment]
@edmoz, me too.  Pushing the big green button.

**Comment by edwindotcom** [comment]
woot!

**Pull request merged**
