### PR TITLE
Update the main site "verify your email address" copy to match that of the dialog.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
issue #1895

### CODE REVIEW

**Comment by seanmonstar** [comment]
these templates don't need to use `gettext`?

**Comment by seanmonstar** [comment]
this looks fine, r+.

@jrgm @lloyd this was supposed to hop into this train?

**Comment by jrgm** [comment]
@seanmonster yeah, ship this for this train.

**Comment by jrgm** [comment]
@seanmonstar See above what I said to @seanmonstar ;-)

**Pull request merged**
